name: Update CniPlugin Version

permissions: write-all

on:
  schedule:
    # each day
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  get_ref:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: main

      - name: Check Version
        run: |
          ./tools/scripts/updateLatestCniPluginVersion.sh ||  exit 1
          if git diff --exit-code  &>/dev/null ; then
              echo "updated=false" >> $GITHUB_ENV
          else
              echo "updated=true" >> $GITHUB_ENV
          fi

      - uses: crazy-max/ghaction-import-gpg@v6
        if: ${{ env.updated == 'true' }}
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Close existing PRs with same title
        if: ${{ env.updated == 'true' }}
        run: |
          PR_TITLE="robot updated CNI plugins version"
          echo "Checking for existing PRs with title: $PR_TITLE"
          # Get list of open PRs with the same title
          EXISTING_PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | \
            jq -r ".[] | select(.title == \"$PR_TITLE\") | .number")
          # Close each existing PR
          for PR_NUMBER in $EXISTING_PRS; do
            echo "Closing existing PR #$PR_NUMBER"
            # Add a comment before closing
            curl -s -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
              -d '{"body":"Closing this PR as a newer version is available."}'
            # Close the PR
            curl -s -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" \
              -d '{"state":"closed"}'
          done

      - name: Create Pull Request
        id: create_pr
        if: ${{ env.updated == 'true' }}
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          title: "robot updated CNI plugins version"
          commit-message: "robot updated CNI plugins version"
          branch-suffix: timestamp
          branch: robot/update_cni_version
          committer: weizhoublue<weizhou.lan@daocloud.io>
          delete-branch: true
          base: main
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: pr/release/robot_update_version
